package com.example.javaproject.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMMON_CHECK_TYPE.
 */
public class CommonCheckType {

    private Long id;
    private String user_name;
    private String check_parent_name;
    private Integer check_parent_id;
    private String check_name;
    private Integer check_id;
    private Integer check_count;

    public CommonCheckType() {
    }

    public CommonCheckType(Long id) {
        this.id = id;
    }

    public CommonCheckType(Long id, String user_name, String check_parent_name, Integer check_parent_id, String check_name, Integer check_id, Integer check_count) {
        this.id = id;
        this.user_name = user_name;
        this.check_parent_name = check_parent_name;
        this.check_parent_id = check_parent_id;
        this.check_name = check_name;
        this.check_id = check_id;
        this.check_count = check_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getCheck_parent_name() {
        return check_parent_name;
    }

    public void setCheck_parent_name(String check_parent_name) {
        this.check_parent_name = check_parent_name;
    }

    public Integer getCheck_parent_id() {
        return check_parent_id;
    }

    public void setCheck_parent_id(Integer check_parent_id) {
        this.check_parent_id = check_parent_id;
    }

    public String getCheck_name() {
        return check_name;
    }

    public void setCheck_name(String check_name) {
        this.check_name = check_name;
    }

    public Integer getCheck_id() {
        return check_id;
    }

    public void setCheck_id(Integer check_id) {
        this.check_id = check_id;
    }

    public Integer getCheck_count() {
        return check_count;
    }

    public void setCheck_count(Integer check_count) {
        this.check_count = check_count;
    }

}
