package com.example.javaproject.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ISSUE_CACHE_ENTITY.
 */
public class IssueCacheEntity {

    private Long id;
    private String userName;
    private String subject;
    private String occurOrgId;
    private String issueKindId;
    private String occurOrgInternalCode;
    private String occurLocation;
    private String mainCharacters;
    private String issueContent;
    private String relatePeopleCount;
    private String isEmergency;
    private String important;
    private String lon;
    private String lat;
    private String occurDate;
    private String uniqueIdForMobile;
    private String files;
    private String firstType;
    private String secondType;
    private String imgFileArray;
    private String soundFileArray;
    private String firstTypeId;
    private String secondTypeId;

    public IssueCacheEntity() {
    }

    public IssueCacheEntity(Long id) {
        this.id = id;
    }

    public IssueCacheEntity(Long id, String userName, String subject, String occurOrgId, String issueKindId, String occurOrgInternalCode, String occurLocation, String mainCharacters, String issueContent, String relatePeopleCount, String isEmergency, String important, String lon, String lat, String occurDate, String uniqueIdForMobile, String files, String firstType, String secondType, String imgFileArray, String soundFileArray, String firstTypeId, String secondTypeId) {
        this.id = id;
        this.userName = userName;
        this.subject = subject;
        this.occurOrgId = occurOrgId;
        this.issueKindId = issueKindId;
        this.occurOrgInternalCode = occurOrgInternalCode;
        this.occurLocation = occurLocation;
        this.mainCharacters = mainCharacters;
        this.issueContent = issueContent;
        this.relatePeopleCount = relatePeopleCount;
        this.isEmergency = isEmergency;
        this.important = important;
        this.lon = lon;
        this.lat = lat;
        this.occurDate = occurDate;
        this.uniqueIdForMobile = uniqueIdForMobile;
        this.files = files;
        this.firstType = firstType;
        this.secondType = secondType;
        this.imgFileArray = imgFileArray;
        this.soundFileArray = soundFileArray;
        this.firstTypeId = firstTypeId;
        this.secondTypeId = secondTypeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getOccurOrgId() {
        return occurOrgId;
    }

    public void setOccurOrgId(String occurOrgId) {
        this.occurOrgId = occurOrgId;
    }

    public String getIssueKindId() {
        return issueKindId;
    }

    public void setIssueKindId(String issueKindId) {
        this.issueKindId = issueKindId;
    }

    public String getOccurOrgInternalCode() {
        return occurOrgInternalCode;
    }

    public void setOccurOrgInternalCode(String occurOrgInternalCode) {
        this.occurOrgInternalCode = occurOrgInternalCode;
    }

    public String getOccurLocation() {
        return occurLocation;
    }

    public void setOccurLocation(String occurLocation) {
        this.occurLocation = occurLocation;
    }

    public String getMainCharacters() {
        return mainCharacters;
    }

    public void setMainCharacters(String mainCharacters) {
        this.mainCharacters = mainCharacters;
    }

    public String getIssueContent() {
        return issueContent;
    }

    public void setIssueContent(String issueContent) {
        this.issueContent = issueContent;
    }

    public String getRelatePeopleCount() {
        return relatePeopleCount;
    }

    public void setRelatePeopleCount(String relatePeopleCount) {
        this.relatePeopleCount = relatePeopleCount;
    }

    public String getIsEmergency() {
        return isEmergency;
    }

    public void setIsEmergency(String isEmergency) {
        this.isEmergency = isEmergency;
    }

    public String getImportant() {
        return important;
    }

    public void setImportant(String important) {
        this.important = important;
    }

    public String getLon() {
        return lon;
    }

    public void setLon(String lon) {
        this.lon = lon;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getOccurDate() {
        return occurDate;
    }

    public void setOccurDate(String occurDate) {
        this.occurDate = occurDate;
    }

    public String getUniqueIdForMobile() {
        return uniqueIdForMobile;
    }

    public void setUniqueIdForMobile(String uniqueIdForMobile) {
        this.uniqueIdForMobile = uniqueIdForMobile;
    }

    public String getFiles() {
        return files;
    }

    public void setFiles(String files) {
        this.files = files;
    }

    public String getFirstType() {
        return firstType;
    }

    public void setFirstType(String firstType) {
        this.firstType = firstType;
    }

    public String getSecondType() {
        return secondType;
    }

    public void setSecondType(String secondType) {
        this.secondType = secondType;
    }

    public String getImgFileArray() {
        return imgFileArray;
    }

    public void setImgFileArray(String imgFileArray) {
        this.imgFileArray = imgFileArray;
    }

    public String getSoundFileArray() {
        return soundFileArray;
    }

    public void setSoundFileArray(String soundFileArray) {
        this.soundFileArray = soundFileArray;
    }

    public String getFirstTypeId() {
        return firstTypeId;
    }

    public void setFirstTypeId(String firstTypeId) {
        this.firstTypeId = firstTypeId;
    }

    public String getSecondTypeId() {
        return secondTypeId;
    }

    public void setSecondTypeId(String secondTypeId) {
        this.secondTypeId = secondTypeId;
    }

}
