package com.example.javaproject.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.javaproject.greendao.PropertyDictEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PROPERTY_DICT_ENTITY.
*/
public class PropertyDictEntityDao extends AbstractDao<PropertyDictEntity, Long> {

    public static final String TABLENAME = "PROPERTY_DICT_ENTITY";

    /**
     * Properties of entity PropertyDictEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PropertyName = new Property(1, String.class, "propertyName", false, "PROPERTY_NAME");
        public final static Property PropertyData = new Property(2, String.class, "propertyData", false, "PROPERTY_DATA");
    };


    public PropertyDictEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PropertyDictEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PROPERTY_DICT_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PROPERTY_NAME' TEXT UNIQUE ," + // 1: propertyName
                "'PROPERTY_DATA' TEXT);"); // 2: propertyData
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PROPERTY_DICT_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PropertyDictEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String propertyName = entity.getPropertyName();
        if (propertyName != null) {
            stmt.bindString(2, propertyName);
        }
 
        String propertyData = entity.getPropertyData();
        if (propertyData != null) {
            stmt.bindString(3, propertyData);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PropertyDictEntity readEntity(Cursor cursor, int offset) {
        PropertyDictEntity entity = new PropertyDictEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // propertyName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // propertyData
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PropertyDictEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPropertyName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPropertyData(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PropertyDictEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PropertyDictEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
